apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: vjd-poc-azredis
  namespace: default
spec:
  clusterServiceClassExternalName: azure-rediscache
  clusterServicePlanExternalName: basic
  parameters:
    location: westus2
    resourceGroup: vjd-poc-rg