apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: pg-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-postgresql-9-6
  clusterServicePlanExternalName: basic
  parameters:
    location: eastus
    resourceGroup: rgServiceCatalog
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"